/**
 * Real tithes & offering history migrated from the standalone ledger app
 * (Desktop/gfc-ledger-app, SQLite "transactions" table).
 *
 * Generated by scripts/migrate-ledger.js - do not hand-edit. Re-run the script
 * to refresh from the source database.
 *
 * Field mapping:
 *   pasok / labas        -> pasok / labas (unchanged, amounts in PHP)
 *   for_pastor (0|1)     -> forPastor (boolean)
 *   created_at           -> createdAt
 *   (computed)           -> balance, running total of pasok - labas
 */

import type { LedgerTransaction } from '../src/types/index.ts';

export const MIGRATED_LEDGER: LedgerTransaction[] = [
  {
    "id": 1,
    "date": "2025-01-05",
    "pasok": 2135,
    "labas": 700,
    "purpose": "",
    "forPastor": false,
    "balance": 1435,
    "createdAt": "2026-08-30 03:29:44"
  },
  {
    "id": 2,
    "date": "2025-01-12",
    "pasok": 2630,
    "labas": 1300,
    "purpose": "",
    "forPastor": false,
    "balance": 2765,
    "createdAt": "2026-08-30 03:31:15"
  },
  {
    "id": 3,
    "date": "2025-01-19",
    "pasok": 1710,
    "labas": 470,
    "purpose": "",
    "forPastor": false,
    "balance": 4005,
    "createdAt": "2026-08-30 03:31:56"
  },
  {
    "id": 4,
    "date": "2025-01-26",
    "pasok": 1816,
    "labas": 3700,
    "purpose": "",
    "forPastor": false,
    "balance": 2121,
    "createdAt": "2026-08-30 03:32:13"
  },
  {
    "id": 5,
    "date": "2025-02-02",
    "pasok": 2539,
    "labas": 747,
    "purpose": "",
    "forPastor": false,
    "balance": 3913,
    "createdAt": "2026-08-30 03:33:23"
  },
  {
    "id": 6,
    "date": "2025-02-09",
    "pasok": 1440,
    "labas": 465,
    "purpose": "",
    "forPastor": false,
    "balance": 4888,
    "createdAt": "2026-08-30 03:38:30"
  },
  {
    "id": 7,
    "date": "2025-02-16",
    "pasok": 1336,
    "labas": 1100,
    "purpose": "",
    "forPastor": false,
    "balance": 5124,
    "createdAt": "2026-08-30 03:34:11"
  },
  {
    "id": 8,
    "date": "2025-02-23",
    "pasok": 2245,
    "labas": 4000,
    "purpose": "",
    "forPastor": false,
    "balance": 3369,
    "createdAt": "2026-08-30 03:34:33"
  },
  {
    "id": 9,
    "date": "2025-03-02",
    "pasok": 2014,
    "labas": 500,
    "purpose": "",
    "forPastor": false,
    "balance": 4883,
    "createdAt": "2026-08-30 03:35:20"
  },
  {
    "id": 10,
    "date": "2025-03-09",
    "pasok": 3012,
    "labas": 1040,
    "purpose": "",
    "forPastor": false,
    "balance": 6855,
    "createdAt": "2026-08-30 03:37:18"
  },
  {
    "id": 11,
    "date": "2025-03-16",
    "pasok": 2412,
    "labas": 1040,
    "purpose": "",
    "forPastor": false,
    "balance": 8227,
    "createdAt": "2026-08-30 03:36:55"
  },
  {
    "id": 12,
    "date": "2025-03-23",
    "pasok": 2251,
    "labas": 1000,
    "purpose": "",
    "forPastor": false,
    "balance": 9478,
    "createdAt": "2026-08-30 03:38:49"
  },
  {
    "id": 13,
    "date": "2025-03-30",
    "pasok": 2710,
    "labas": 4000,
    "purpose": "",
    "forPastor": false,
    "balance": 8188,
    "createdAt": "2026-08-30 03:39:02"
  },
  {
    "id": 14,
    "date": "2025-04-06",
    "pasok": 2197,
    "labas": 656,
    "purpose": "",
    "forPastor": false,
    "balance": 9729,
    "createdAt": "2026-08-30 03:39:27"
  },
  {
    "id": 15,
    "date": "2025-04-13",
    "pasok": 1579,
    "labas": 1040,
    "purpose": "",
    "forPastor": false,
    "balance": 10268,
    "createdAt": "2026-08-30 03:40:46"
  },
  {
    "id": 16,
    "date": "2025-04-20",
    "pasok": 3160,
    "labas": 3090,
    "purpose": "",
    "forPastor": false,
    "balance": 10338,
    "createdAt": "2026-08-30 03:41:03"
  },
  {
    "id": 17,
    "date": "2025-04-27",
    "pasok": 3617,
    "labas": 1500,
    "purpose": "",
    "forPastor": false,
    "balance": 12455,
    "createdAt": "2026-08-30 03:41:24"
  },
  {
    "id": 18,
    "date": "2025-05-04",
    "pasok": 1552,
    "labas": 600,
    "purpose": "",
    "forPastor": false,
    "balance": 13407,
    "createdAt": "2026-08-30 03:45:20"
  },
  {
    "id": 19,
    "date": "2025-05-11",
    "pasok": 4533,
    "labas": 200,
    "purpose": "",
    "forPastor": false,
    "balance": 17740,
    "createdAt": "2026-08-30 03:45:31"
  },
  {
    "id": 20,
    "date": "2025-05-18",
    "pasok": 3903,
    "labas": 1200,
    "purpose": "",
    "forPastor": false,
    "balance": 20443,
    "createdAt": "2026-08-30 03:45:55"
  },
  {
    "id": 21,
    "date": "2025-05-25",
    "pasok": 2259,
    "labas": 4400,
    "purpose": "",
    "forPastor": false,
    "balance": 18302,
    "createdAt": "2026-08-30 03:46:18"
  },
  {
    "id": 22,
    "date": "2025-06-01",
    "pasok": 3230,
    "labas": 500,
    "purpose": "",
    "forPastor": false,
    "balance": 21032,
    "createdAt": "2026-08-30 03:46:37"
  },
  {
    "id": 23,
    "date": "2025-06-08",
    "pasok": 1760,
    "labas": 500,
    "purpose": "",
    "forPastor": false,
    "balance": 22292,
    "createdAt": "2026-08-30 03:46:46"
  },
  {
    "id": 24,
    "date": "2025-06-15",
    "pasok": 2792,
    "labas": 1830,
    "purpose": "",
    "forPastor": false,
    "balance": 23254,
    "createdAt": "2026-08-30 03:47:02"
  },
  {
    "id": 25,
    "date": "2025-06-22",
    "pasok": 2100,
    "labas": 400,
    "purpose": "",
    "forPastor": false,
    "balance": 24954,
    "createdAt": "2026-08-30 03:47:14"
  },
  {
    "id": 26,
    "date": "2025-06-29",
    "pasok": 2714,
    "labas": 1080,
    "purpose": "",
    "forPastor": false,
    "balance": 26588,
    "createdAt": "2026-08-30 03:47:40"
  },
  {
    "id": 27,
    "date": "2025-07-06",
    "pasok": 2858,
    "labas": 850,
    "purpose": "",
    "forPastor": false,
    "balance": 28596,
    "createdAt": "2026-08-30 03:47:54"
  },
  {
    "id": 28,
    "date": "2025-07-13",
    "pasok": 2105,
    "labas": 0,
    "purpose": "",
    "forPastor": false,
    "balance": 30701,
    "createdAt": "2026-08-30 03:48:08"
  },
  {
    "id": 29,
    "date": "2025-07-20",
    "pasok": 2154,
    "labas": 820,
    "purpose": "",
    "forPastor": false,
    "balance": 32035,
    "createdAt": "2026-08-30 03:48:25"
  },
  {
    "id": 30,
    "date": "2025-07-27",
    "pasok": 2205,
    "labas": 3500,
    "purpose": "",
    "forPastor": false,
    "balance": 30740,
    "createdAt": "2026-08-30 03:48:40"
  },
  {
    "id": 31,
    "date": "2025-08-03",
    "pasok": 1648,
    "labas": 0,
    "purpose": "",
    "forPastor": false,
    "balance": 32388,
    "createdAt": "2026-08-30 03:49:11"
  },
  {
    "id": 32,
    "date": "2025-08-10",
    "pasok": 1152,
    "labas": 0,
    "purpose": "",
    "forPastor": false,
    "balance": 33540,
    "createdAt": "2026-08-30 03:49:20"
  },
  {
    "id": 33,
    "date": "2025-08-17",
    "pasok": 1487,
    "labas": 900,
    "purpose": "",
    "forPastor": false,
    "balance": 34127,
    "createdAt": "2026-08-30 03:49:39"
  },
  {
    "id": 34,
    "date": "2025-08-24",
    "pasok": 321,
    "labas": 300,
    "purpose": "",
    "forPastor": false,
    "balance": 34148,
    "createdAt": "2026-08-30 03:49:52"
  },
  {
    "id": 35,
    "date": "2025-08-31",
    "pasok": 1537,
    "labas": 3700,
    "purpose": "",
    "forPastor": false,
    "balance": 31985,
    "createdAt": "2026-08-30 03:50:12"
  },
  {
    "id": 36,
    "date": "2025-09-07",
    "pasok": 1317,
    "labas": 0,
    "purpose": "",
    "forPastor": false,
    "balance": 33302,
    "createdAt": "2026-08-30 03:50:35"
  },
  {
    "id": 37,
    "date": "2025-09-14",
    "pasok": 700,
    "labas": 0,
    "purpose": "",
    "forPastor": false,
    "balance": 34002,
    "createdAt": "2026-08-30 03:50:43"
  },
  {
    "id": 38,
    "date": "2025-09-21",
    "pasok": 962,
    "labas": 300,
    "purpose": "",
    "forPastor": false,
    "balance": 34664,
    "createdAt": "2026-08-30 03:50:54"
  },
  {
    "id": 39,
    "date": "2025-09-28",
    "pasok": 1,
    "labas": 0,
    "purpose": "Anniversary",
    "forPastor": false,
    "balance": 34665,
    "createdAt": "2026-08-30 03:51:35"
  },
  {
    "id": 40,
    "date": "2025-10-05",
    "pasok": 1150,
    "labas": 0,
    "purpose": "",
    "forPastor": false,
    "balance": 35815,
    "createdAt": "2026-08-30 03:51:52"
  },
  {
    "id": 41,
    "date": "2025-10-12",
    "pasok": 1956,
    "labas": 0,
    "purpose": "",
    "forPastor": false,
    "balance": 37771,
    "createdAt": "2026-08-30 03:52:02"
  },
  {
    "id": 42,
    "date": "2025-10-19",
    "pasok": 1712,
    "labas": 300,
    "purpose": "",
    "forPastor": false,
    "balance": 39183,
    "createdAt": "2026-08-30 03:52:12"
  },
  {
    "id": 43,
    "date": "2025-10-26",
    "pasok": 2031,
    "labas": 3700,
    "purpose": "",
    "forPastor": false,
    "balance": 37514,
    "createdAt": "2026-08-30 03:52:37"
  },
  {
    "id": 44,
    "date": "2025-11-02",
    "pasok": 1913,
    "labas": 0,
    "purpose": "",
    "forPastor": false,
    "balance": 39427,
    "createdAt": "2026-08-30 03:53:23"
  },
  {
    "id": 45,
    "date": "2025-11-09",
    "pasok": 1751,
    "labas": 0,
    "purpose": "",
    "forPastor": false,
    "balance": 41178,
    "createdAt": "2026-08-30 03:57:36"
  },
  {
    "id": 46,
    "date": "2025-11-16",
    "pasok": 1692,
    "labas": 0,
    "purpose": "",
    "forPastor": false,
    "balance": 42870,
    "createdAt": "2026-08-30 03:57:57"
  },
  {
    "id": 47,
    "date": "2025-11-23",
    "pasok": 1204,
    "labas": 960,
    "purpose": "",
    "forPastor": false,
    "balance": 43114,
    "createdAt": "2026-08-30 03:58:25"
  },
  {
    "id": 48,
    "date": "2025-11-29",
    "pasok": 1891,
    "labas": 6330,
    "purpose": "",
    "forPastor": false,
    "balance": 38675,
    "createdAt": "2026-08-30 04:00:48"
  },
  {
    "id": 49,
    "date": "2025-12-07",
    "pasok": 1086,
    "labas": 86,
    "purpose": "",
    "forPastor": false,
    "balance": 39675,
    "createdAt": "2026-08-30 04:03:04"
  },
  {
    "id": 50,
    "date": "2025-12-14",
    "pasok": 3319,
    "labas": 3500,
    "purpose": "",
    "forPastor": false,
    "balance": 39494,
    "createdAt": "2026-08-30 04:03:36"
  },
  {
    "id": 51,
    "date": "2025-12-21",
    "pasok": 3309,
    "labas": 120,
    "purpose": "",
    "forPastor": false,
    "balance": 42683,
    "createdAt": "2026-08-30 04:03:58"
  },
  {
    "id": 52,
    "date": "2025-12-28",
    "pasok": 1930,
    "labas": 3800,
    "purpose": "",
    "forPastor": false,
    "balance": 40813,
    "createdAt": "2026-08-30 04:04:38"
  },
  {
    "id": 53,
    "date": "2026-08-30",
    "pasok": 500,
    "labas": 0,
    "purpose": "",
    "forPastor": false,
    "balance": 41313,
    "createdAt": "2026-08-30 12:21:59"
  },
  {
    "id": 54,
    "date": "2027-08-30",
    "pasok": 5000,
    "labas": 0,
    "purpose": "",
    "forPastor": false,
    "balance": 46313,
    "createdAt": "2026-08-30 12:22:52"
  },
  {
    "id": 55,
    "date": "2028-08-30",
    "pasok": 10000,
    "labas": 0,
    "purpose": "",
    "forPastor": false,
    "balance": 56313,
    "createdAt": "2026-08-30 12:23:13"
  },
  {
    "id": 56,
    "date": "2029-08-30",
    "pasok": 10000,
    "labas": 0,
    "purpose": "",
    "forPastor": false,
    "balance": 66313,
    "createdAt": "2026-08-30 12:23:44"
  },
  {
    "id": 57,
    "date": "2030-08-30",
    "pasok": 10000,
    "labas": 0,
    "purpose": "",
    "forPastor": false,
    "balance": 76313,
    "createdAt": "2026-08-30 12:24:06"
  }
];
