/**
 * One-off migration: Desktop/gfc-ledger-app (SQLite) -> admin ledger.
 *
 * Reads data/ledger.db from the standalone ledger app and emits a TypeScript
 * seed, preserving every real transaction. The running balance is recomputed
 * from the real figures rather than copied.
 */
const fs = require('fs');
const path = require('path');
const { DatabaseSync } = require('node:sqlite');

const SRC = 'C:/Users/abcd/Desktop/gfc-ledger-app';
const OUT = 'C:/Users/abcd/Downloads/gfc-admin/server/ledger.seed.ts';

const db = new DatabaseSync(path.join(SRC, 'data/ledger.db'), { readOnly: true });
const rows = db
  .prepare('SELECT id, date, pasok, labas, purpose, for_pastor, created_at FROM transactions ORDER BY date ASC, id ASC')
  .all();
db.close();

let balance = 0;
const txs = rows.map((r, i) => {
  const pasok = Number(r.pasok) || 0;
  const labas = Number(r.labas) || 0;
  balance += pasok - labas;
  return {
    id: i + 1,
    date: r.date,
    pasok,
    labas,
    purpose: r.purpose || '',
    forPastor: Number(r.for_pastor) === 1,
    balance,
    createdAt: r.created_at || `${r.date}T10:00:00Z`,
  };
});

const totalIn = txs.reduce((a, t) => a + t.pasok, 0);
const totalOut = txs.reduce((a, t) => a + t.labas, 0);

const header = `/**
 * Real tithes & offering history migrated from the standalone ledger app
 * (Desktop/gfc-ledger-app, SQLite "transactions" table).
 *
 * Generated by scripts/migrate-ledger.js - do not hand-edit. Re-run the script
 * to refresh from the source database.
 *
 * Field mapping:
 *   pasok / labas        -> pasok / labas (unchanged, amounts in PHP)
 *   for_pastor (0|1)     -> forPastor (boolean)
 *   created_at           -> createdAt
 *   (computed)           -> balance, running total of pasok - labas
 */

export const MIGRATED_LEDGER: LedgerTransaction[] = `;

fs.writeFileSync(OUT, header + JSON.stringify(txs, null, 2) + ';\n');

console.log('migrated transactions:', txs.length);
console.log('total in :', totalIn.toLocaleString());
console.log('total out:', totalOut.toLocaleString());
console.log('net      :', (totalIn - totalOut).toLocaleString());
console.log('range    :', txs[0].date, '->', txs[txs.length - 1].date);
console.log('written  :', OUT);
